### PR TITLE
Added 4th Test Case

### PR DESCRIPTION
**Pull request by zharry**
Here's a general overview of what's being tested in each section/line of the test case:

| Line(s) | Objective |
| --- | --- |
| 1-9 | Empty Tree Testing |
| 10-15 | Double Precision Testing |
| 16-19 | Single Node Min/Max/Total Testing |
| 21-60 | Balanced Tree Testing |
| 61-80 | Degenerate Tree Testing |
| 81-91 | General Insertion Testing |
| 92-100 | Duplicate non-coordinate value Testing |

Disclaimer: I **did not** write the output file by hand, so I'm not actually sure if these answers are correct. 

If anyone else can run the case and see if they get the same output that would be wonderful! If you get a different answer, an error, or disagree with a test case make a comment and I'll run through the tree by hand and see what's wrong.

### CODE REVIEW

**Comment by Shreyas15srivatsa** [comment]
Hey Harry, I ran these test cases but I'm getting a different output for lines - **82,83,84,85,86,87, and 99**. Since the tree has been cleared before the insertions (82-84), shouldn't the insertions be successful? Also, in line 99, the output says "found city2" but there are two city2's of coordinates (2,2) and (2,-2) but not at (2,-1). 

Otherwise, everything else matched with my outputs.

P.S: In the attached image, the left side is my output and the right side is yours

image

**Comment by zharry** [comment]
Alright, there was a small issue in the test case, which I have fixed. Line 99 is in fact a mistake in my code, and that change has been reflected in the output.

But I still don't get the same in-order traversal as you, shouldn't it start with city 7 because that's the NW most city?
That is to say line 86 of the output should be:
`city7 city6 city9 city5 city10 city4 city3 city2 city1 city8 city11 `
(This traversal which should also affect 87 and 89)

image

I'm using the same rules as the ones specified in the document for same x/y coords
image

**Comment by Shreyas15srivatsa** [comment]
Looks good now! All our outputs match.

**Comment by zharry** [comment]
Alright, great! We'll merge it in when we can get one more reviewer.

**Comment by ansar-z-khan** [comment]
Based on Tiuley's comment regarding double equality on Learn. Two floating-point numbers are considered if they are within three decimal places of each other.

Hence, the following two cities should be considered equal and city2 should fail when inserted. 

`i city1;1.000000001;1.000000001;100;100;100
i city2;1;1;100;100;100`

Screen Shot 2019-11-03 at 3 51 47 PM

**Comment by zharry** [comment]
I see... the test case that I've written is more of a test that values were stored as doubles and not float types. And so that if those tests pass, the following tests can just use integers.

I'm sure that if double was used and all test cases they give only test up to 3 decimal points, it would pass regardless. I'm going to merge this in, and if anyone has any additional problems or a lot of people end up getting a different output for line 11, I'll revisit this.

**Pull request merged**
