### PR TITLE
Add test case

### PR DESCRIPTION
**Pull request by ansar-z-khan**
Used to test path planning part of project.

### CODE REVIEW

**Comment by zharry** [comment]
I've taken a look at your output, and it seems like there is an extra "E" as the second node in every print_path output.

Additionally, I've also run did a run and my outputs for the following are different:
```
(Line 164-165)
Moscow Chongqing Washington Chennai Hanoi
shortest distance Moscow to Hanoi 43.6981
(Line 176-177)
Karachi Kolkata Ahmedabad Wuhan Jakarta Chennai HoChiMinhCity
shortest distance Karachi to HoChiMinhCity 74.804
(Line 212-213)
Chongqing Washington Chennai Jakarta
shortest distance Chongqing to Jakarta 39.6775
(Line 220-221)
Ahmedabad Wuhan Jakarta Chennai Washington
shortest distance Ahmedabad to Washington 33.8712
(Line 232-233)
Atlanta Ahmedabad Wuhan Jakarta Chennai Hanoi LosAngeles
shortest distance Atlanta to LosAngeles 116.808
```
I'm gonna double-check them now, and I'll edit this comment if something was wrong.

**Comment by zharry** [comment]
Here's the difference between our two outputs: https://diffchecker.com/CIZGmszk
I'm only going to go through the first mismatch as the rest should have the same concept.
--
Okay, so taking a look at line 164/165, your output specifies:
```
Moscow Chongqing Washington Jakarta Wuhan Hanoi
shortest distance Moscow to Hanoi 71.3999
```
Meaning the path it took was:
```
(101) setd Moscow;Chongqing;6.74943637221
(59) setd Chongqing;Washington;28.403427695
(51) setd Washington;Jakarta;37.0286177616 // This is unsed as it has been changed in line 87
(87) setd Jakarta;Washington;20.2766434534
(115) setd Wuhan;Jakarta;0.340089269701
(110) setd Hanoi;Wuhan;15.6303375934
```
So, according to your output, the distance is around 71.403, which matches your shortest distance output. (Idk where I was going with this, but keep reading...)

---
Now, my output says:
```
Moscow Chongqing Washington Chennai Hanoi
shortest distance Moscow to Hanoi 43.6981
```
Meaning the path it took was:
```
(101) setd Moscow;Chongqing;6.74943637221
(59) setd Chongqing;Washington;28.403427695
(125) setd Chennai;Washington;7.87278533784
(50) setd Hanoi;Chennai;0.672479876677
```
So, according to my output, the distance is around 43.69, which matches my shortest distance output.

Because we were able to re-build both of our paths and know that both paths are in fact traversable, we can conclude that because the output of the Dijkstra's algorithm should output the minimum distance, that there is likely a mistake in the output file.

**Comment by ansar-z-khan** [comment]
Yea, I just looked at my code, there is a bug in my implementation. Your output should be correct.

**Comment by Shreyas15srivatsa** [comment]
Outputs match for test08 and test09.

**Pull request merged**
