### PR TITLE
Added Test04 and Test05

### PR DESCRIPTION
**Pull request by zharry**
Test 4 is just a simple combination of tests 1-3, meaning I put clear between each of the files and concatenated them together.

Test 5 is slightly more complicated, the first few lines just test basic failure functionality. Past around line 25 it's a more comprehensive Dijkstra's test. (See image below for the graph)
- At first, only the top graph is created, without the dotted connections, then some queries are performed.
- Then the dotted edges are made
- At around line 60, the bottom graph is added
- Then edge between 9 and 11 is updated, and additional queries are performed
- Finally, node 12 (connected to nothing), is added
IMG_20191120_154049

A few concerns again,
Line 14, tests what happens when the `degree` command is used on a city that is not inserted. What should happen here? In my output, it just says the degree is zero.
Lines 23-24, tests what happens when we try to query distance/path between the same city to itself, I also have no idea what's supposed to happen here.
Finally, I'm not actually certain of the correctness of the output file, if someone can verify them that would be great!

### CODE REVIEW

**Comment by Shreyas15srivatsa** [comment]
Hey Harry, a few things
1. When the city does not exist, the degree command should print failure (line 14)
2. On line 48, both paths 1->4->7 and 1->4->2->7 have the same total weight, so I'm not sure which one to choose here. My output says 1->4->7 while yours is the other
3. The same as above on line 59
4. On line 80, my path is 9->11 and not 9->10->8->11. Same case as above

**Comment by zharry** [comment]
Okay, I fixed line 14, we'll see about the path printing...

**Comment by Shreyas15srivatsa** [comment]
According to the latest Piazza post, the degree command should now print "**not found**" if the city does not exist.

**Comment by zharry** [comment]
Ah, I see, my line 48 becomes `1 4 7`, line 59 becomes `1 4 7`, and line 80 becomes `9 11`, when I change my Dijkstra condition from `<=` to `<`.

And by the ambiguity of https://piazza.com/class/k0o65c70lop3kl?cid=95, I'm just gonna go and say it doesn't matter cause they probably won't give a case like this anyways.

**Comment by zharry** [comment]
Lmao, I messed up, turns out I'm not that good with Git.

**Pull request merged**
